import type { EndpointHealth, EventStatus } from './types'

/**
 * The whole interface in both languages. Spanish is the product's home voice;
 * English is how it travels. Keep this file free of server imports: server
 * pages read the visitor's language from a cookie (see lang.ts) and pass it
 * down, so every string renders correctly on the first paint.
 *
 * `en` is typed as `typeof es`, so forgetting a translation is a type error.
 */

export type Lang = 'es' | 'en'
export const LANGS: Lang[] = ['es', 'en']

const es = {
  meta: {
    title: 'Acuse — ningún evento se pierde',
    description:
      'Recibe los webhooks de tus integraciones, reintenta los que fallan y te muestra cuántos rescató.',
  },
  shell: {
    tagline: 'registro de entregas — ningún evento se pierde',
    demoNote: 'Instancia de demostración · el tráfico lo genera',
    themeNames: { instrumento: 'instrumento', libro: 'libro' },
  },
  status: {
    delivered: 'entregado',
    pending: 'reintentando',
    dead: 'sin entregar',
    queued: 'en cola',
  } as Record<EventStatus | 'queued', string>,
  health: {
    healthy: 'sano',
    degraded: 'inestable',
    down: 'caído',
    idle: 'sin tráfico',
  } as Record<EndpointHealth['health'], string>,
  actions: {
    processQueue: 'Procesar cola ahora',
    processing: 'procesando…',
    recorded: 'asentado',
    redeliver: 'Reenviar ahora',
    redelivered: 'reenviado',
    pause: 'Pausar entregas',
    resume: 'Reanudar entregas',
    done: 'hecho',
  },
  dashboard: {
    headline: 'Eventos rescatados',
    headlineDesc: (n: string) =>
      `Entregas que fallaron en el primer intento y terminaron llegando gracias a los reintentos. Sin Acuse en el medio, estas ${n} se perdían en silencio.`,
    barFirstTry: 'primer intento',
    barRescued: 'rescatados',
    barRetrying: 'en reintento',
    barDead: 'sin entregar',
    noteOne: (name: string) => `«${name}» dejó de responder.`,
    noteMany: (count: number, names: string) =>
      `${count} integraciones dejaron de responder: ${names}.`,
    noteTail:
      'Los eventos siguen guardados y se reintentan solos; esta anotación aparece antes de que se pierda nada.',
    received: 'Eventos recibidos',
    delivered: 'Entregados',
    ofTotal: (pct: string) => `${pct} del total`,
    retrying: 'En reintento',
    nextRetry: (when: string) => `próximo ${when}`,
    queueEmpty: 'cola vacía',
    dead: 'Sin entregar',
    needHuman: 'necesitan una persona',
    none: 'ninguno',
    integrations: 'Integraciones',
    colName: 'Nombre',
    colStatus: 'Estado',
    colReceived: 'Recibidos',
    colRescued: 'Rescatados',
    colDead: 'Sin entregar',
    colLastDelivery: 'Última entrega',
    paused: '(en pausa)',
    latestEvents: 'Últimos eventos',
    viewAll: 'ver todos →',
    emptyIntegrations: 'No hay integraciones todavía. Corré',
    emptyEvents: 'Todavía no llegó ningún evento. Corré',
    attempts: (n: number) =>
      n === 0 ? 'sin intentos' : `${n} ${n === 1 ? 'intento' : 'intentos'}`,
  },
  events: {
    back: 'volver al panel',
    title: 'Eventos',
    filterAll: 'Todos',
    filterPending: 'En reintento',
    filterDead: 'Sin entregar',
    filterDelivered: 'Entregados',
    colEvent: 'Evento',
    colIntegration: 'Integración',
    colStatus: 'Estado',
    colAttempts: 'Intentos',
    colReceived: 'Recibido',
    empty: 'No hay eventos con ese estado.',
  },
  event: {
    received: 'Recibido',
    delivered: 'Entregado',
    attempts: 'Intentos',
    nextAttempt: 'Próximo intento',
    lastError: 'Último error',
    attemptsTitle: 'Intentos de entrega',
    noAttempts: 'Todavía no se intentó entregar. El evento ya está guardado.',
    payloadTitle: 'Contenido recibido',
    noResponse: 'sin respuesta',
  },
  endpoint: {
    ingestLabel: 'Le pasás esta URL al que manda el webhook',
    deliverLabel: 'Y nosotros entregamos acá',
    retrySentence: (max: number, schedule: string) =>
      `Si el destino no contesta, reintentamos ${max} veces separando cada intento: ${schedule}. Después queda marcado como sin entregar y esperando a una persona.`,
    received: 'Recibidos',
    delivered: 'Entregados',
    rescued: 'Rescatados',
    dead: 'Sin entregar',
    eventsTitle: 'Eventos de esta integración',
    empty: 'Todavía no llegó ningún evento acá.',
    attemptsShort: (n: number) => `${n} int.`,
  },
}

const en: typeof es = {
  meta: {
    title: 'Acuse — no event gets lost',
    description:
      'Receives your integrations’ webhooks, retries the failed ones and shows you how many it rescued.',
  },
  shell: {
    tagline: 'delivery ledger — no event gets lost',
    demoNote: 'Demo instance · traffic is generated by',
    themeNames: { instrumento: 'instrument', libro: 'ledger' },
  },
  status: {
    delivered: 'delivered',
    pending: 'retrying',
    dead: 'undelivered',
    queued: 'queued',
  } as Record<EventStatus | 'queued', string>,
  health: {
    healthy: 'healthy',
    degraded: 'flaky',
    down: 'down',
    idle: 'no traffic',
  } as Record<EndpointHealth['health'], string>,
  actions: {
    processQueue: 'Process queue now',
    processing: 'processing…',
    recorded: 'recorded',
    redeliver: 'Redeliver now',
    redelivered: 'redelivered',
    pause: 'Pause deliveries',
    resume: 'Resume deliveries',
    done: 'done',
  },
  dashboard: {
    headline: 'Events rescued',
    headlineDesc: (n: string) =>
      `Deliveries that failed on the first attempt and still made it, thanks to the retries. Without Acuse in the middle, these ${n} were silently lost.`,
    barFirstTry: 'first attempt',
    barRescued: 'rescued',
    barRetrying: 'retrying',
    barDead: 'undelivered',
    noteOne: (name: string) => `“${name}” stopped responding.`,
    noteMany: (count: number, names: string) =>
      `${count} integrations stopped responding: ${names}.`,
    noteTail:
      'Their events are safely stored and retrying on their own; this note appears before anything is lost.',
    received: 'Events received',
    delivered: 'Delivered',
    ofTotal: (pct: string) => `${pct} of total`,
    retrying: 'Retrying',
    nextRetry: (when: string) => `next ${when}`,
    queueEmpty: 'queue empty',
    dead: 'Undelivered',
    needHuman: 'need a human',
    none: 'none',
    integrations: 'Integrations',
    colName: 'Name',
    colStatus: 'Status',
    colReceived: 'Received',
    colRescued: 'Rescued',
    colDead: 'Undelivered',
    colLastDelivery: 'Last delivery',
    paused: '(paused)',
    latestEvents: 'Latest events',
    viewAll: 'view all →',
    emptyIntegrations: 'No integrations yet. Run',
    emptyEvents: 'No events yet. Run',
    attempts: (n: number) =>
      n === 0 ? 'no attempts' : `${n} ${n === 1 ? 'attempt' : 'attempts'}`,
  },
  events: {
    back: 'back to dashboard',
    title: 'Events',
    filterAll: 'All',
    filterPending: 'Retrying',
    filterDead: 'Undelivered',
    filterDelivered: 'Delivered',
    colEvent: 'Event',
    colIntegration: 'Integration',
    colStatus: 'Status',
    colAttempts: 'Attempts',
    colReceived: 'Received',
    empty: 'No events with that status.',
  },
  event: {
    received: 'Received',
    delivered: 'Delivered',
    attempts: 'Attempts',
    nextAttempt: 'Next attempt',
    lastError: 'Last error',
    attemptsTitle: 'Delivery attempts',
    noAttempts: 'No delivery attempted yet. The event is already stored.',
    payloadTitle: 'Received payload',
    noResponse: 'no response',
  },
  endpoint: {
    ingestLabel: 'Give this URL to whatever sends the webhook',
    deliverLabel: 'And we deliver here',
    retrySentence: (max: number, schedule: string) =>
      `If the destination does not answer, we retry ${max} times, spacing the attempts: ${schedule}. After that the event is marked undelivered, waiting for a human.`,
    received: 'Received',
    delivered: 'Delivered',
    rescued: 'Rescued',
    dead: 'Undelivered',
    eventsTitle: 'Events of this integration',
    empty: 'No events here yet.',
    attemptsShort: (n: number) => `${n} att.`,
  },
}

export const dict: Record<Lang, typeof es> = { es, en }
